function local_test

imgPath = 'data/local_seg_test/sparse.tif';

%% Load the image.
[oriImg, imgSize] = tiff.imread(imgPath, true);

%% Configure KeyPressFcn on active figure.
close all;
h = figure('Name', 'Result', 'NumberTitle', 'off');

currIdx = 1;
prevIdx = -1;

    function keyPressEvent(~, event)
    %%KEYPRESSEVENT Handle the keypress event generated by user key input.

    switch(event.Key)
        case {'q', 'Q'}
            % Quit
            currIdx = -1;
        case {'w', 'W'}
            % Previous
            currIdx = currIdx-1;
        case {'s', 'S'}
            % Next
            currIdx = currIdx+1;
    end

    end
set(gcf, 'KeyPressFcn', @keyPressEvent);

while currIdx <= imgSize(3)
    if (currIdx < 0) || ~ishandle(h)
        break;
    end
    
    if prevIdx ~= currIdx
        j = oriImg(:, :, currIdx);
        imagesc(j);
        axis equal tight;
        drawnow;
        set(gcf, 'Name', ['Layer ', num2str(currIdx)]);
        prevIdx = currIdx;
    end
    
    pause(0.25);
end

end



